micronaut:
  server:
    port: 8080
  application:
    name: WindSensor
    default-charset: UTF-8
  security:
    enabled: ${SECURITY_ENABLED:false}
    redirect:
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
  metrics:
    enabled: true

endpoints:
  metrics:
    enabled: true
  loggers:
    enabled: true
    write-sensitive: false

wind-providers:
  windy:
    url: https://api.windyapp.co/apiV9.php?method=getMeteostationDataAndInfo&meteostationID=%s


