micronaut:
  server:
    port: 8080
    ssl:
      enabled: ${SSL_ENABLED:true}
      ssl-redirect: false
      port: 443
      buildSelfSigned: false
      key-store:
        path: ${KEY_STORE_PATH:`classpath:keystore.p12`}
        password: ${KEY_STORE_PASSWORD:changeit}
        type: ${KEY_STORE_TYPE:PKCS12}
        alias: micronaut
  application:
    name: WindSensor
    default-charset: UTF-8
  security:
    enabled: ${SECURITY_ENABLED:false}
    redirect:
      forbidden:
        enabled: false
      unauthorized:
        enabled: false
  metrics:
    enabled: true

endpoints:
  metrics:
    enabled: true
  loggers:
    enabled: true
    write-sensitive: false

wind-providers:
  windy:
    url: https://api.windyapp.co/apiV9.php?method=getMeteostationDataAndInfo&meteostationID=%s


